### ISSUE TITLE
Potential optimizations

### ISSUE THREAD

**Issue by the-r3dacted** [Mibo5354/i9300_builds#6]
Maybe you've already tried these, maybe they're not applicable to Exynos or require a lot of tweaking, but I found these on a LineageOS 14.1 ROM for the S5.
https://forum.xda-developers.com/t/rom-7-1-2-klte-optimized-lineageoms-14-1-for-the-samsung-galaxy-s5.3942599/
"-Built with latest Linaro toolchain GCC 7.4.1 snapshot and SDClang 6.0.9
-O3 GCC optimizations applied on ROM, O2 on Kernel
-Graphite optimizations applied on ROM"

**Comment by Mibo5354** [comment]
I don't have time, build it yourself if you're interested. Using my current builds with microg is good enough for me.
