### ISSUE TITLE
I9305 build?

### ISSUE THREAD

**Issue by the-r3dacted** [Mibo5354/i9300_builds#7]
They seem to have the same hardware aside form the I9305 having LTE and depending on the model an extra GB of memory. Is there any big reason to not make a I9305 build?

**Comment by Mibo5354** [comment]
I don't have a i9305, someone else can build it.

**Comment by the-r3dacted** [comment]
Now I'm dumb, say I get a I9305 or want to try making a build with the newer compiler and whatever. How exactly would I go about trying that?

**Comment by Mibo5354** [comment]
Easiest way is to use the https://github.com/lineageos4microg/docker-lineage-cicd docker image.
The build command I used is on the README of this repo. Just replace i9300 with i9305.
Also use my local manifests, https://github.com/Mibo5354/i9300_builds/tree/master/local_manifests except for [roomservice.xml](https://github.com/Mibo5354/i9300_builds/blob/master/local_manifests/roomservice.xml)
The official lineageOS repo doesn't have all the security patches merged.

Alternatively there are also [these instructions](https://wiki.lineageos.org/devices/i9305/build) from LineageOS.
